In [256]:
import pandas as pd
from pymongo import MongoClient
import re
pd.set_option('display.max_colwidth', None)
client = MongoClient("mongodb://localhost:27017/")
db = client["LaptopDataDB"]
raw_collection = db["laptops"]

df = pd.DataFrame(list(raw_collection.find({}, {"_id": 0})))

In [257]:
df

,brand,id,url_product,name_product,price,img_product,cpu_name,gpu,ram_info,ram_type,...,resolution,color_gamut,refresh_rate,display_technology,port,webcam,battery_specifications,physical_dimensions,material,release_year
0,ASUS,357993,https://www.thegioididong.com/laptop/asus-vivobook-go-e1504fa-r5-7520u-bq1160w,Asus Vivobook Go E1504FA R5 7520U (BQ1160W),14.390.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/357993/asus-vivobook-go-e1504fa-r5-7520u-bq1160w-thumb-638966564562227379-600x600.jpg,None,"Card tích hợp, - AMD Radeon Graphics",16 GB,LPDDR5 (Onboard),...,Full HD (1920 x 1080),None,60Hz,Chống chói Anti Glare,"1 x USB 3.2, 1 x USB 2.0, Jack tai nghe 3.5 mm, 1 x USB 3.2 Gen 1 Type-C, HDMI 1.4",HD webcam,3-cell Li-ion - 42 WHrs,Dài 360.3 mm - Rộng 232.5 mm - Dày 17.9 mm - 1.63 kg,Vỏ nhựa,2025
1,ASUS,334792,https://www.thegioididong.com/laptop/asus-vivobook-15-x1504va-i3-nj1634w,Asus Vivobook 15 X1504VA i3 1315U (NJ1634W),12.990.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/334792/asus-vivobook-15-x1504va-i3-nj1634w-thumb-638760891054481940-600x600.jpg,None,"Card tích hợp, -, Intel UHD Graphics",8 GB,DDR4 (1 khe 8 GB + 1 khe rời),...,Full HD (1920 x 1080),45% NTSC,60Hz,"Chống chói Anti Glare, LED Backlit, 250 nits","1 x USB 2.0, Jack tai nghe 3.5 mm, 2 x USB 3.2, HDMI, USB Type-C",HD webcam,"3-cell Li-ion, 42 Wh",Dài 359.7 mm - Rộng 232.5 mm - Dày 17.9 mm - 1.7 kg,Vỏ nhựa,2025
2,ASUS,338323,https://www.thegioididong.com/laptop/asus-x1504va-core-5-bq185ws,Asus Vivobook 15 X1504VA Core 5 120U (BQ185WS),19.690.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/338323/asus-x1504va-core-5-bq185ws-thumb2-638929335505560781-600x600.jpg,None,"Card tích hợp, - Intel Graphics",16 GB,DDR4 (8 GB onboard + 1 khe 8 GB),...,Full HD (1920 x 1080),45% NTSC,60Hz,"Chống chói Anti Glare, LED Backlit, 250 nits","1 x USB 2.0, Jack tai nghe 3.5 mm, 2 x USB 3.2, HDMI, USB Type-C",HD webcam,"3-cell Li-ion, 42 Wh",Dài 359.7 mm - Rộng 232.5 mm - Dày 17.9 mm - 1.7 kg,Vỏ nhựa,2025
3,ASUS,360420,https://www.thegioididong.com/laptop/asus-vivobook-15-x1504va-core-7-150u-bq295w,Asus Vivobook 15 X1504VA Core 7 150U (BQ295W),22.390.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/360420/asus-vivobook-15-x1504va-core-7-150u-bq295w-thumb-639016922618560744-600x600.jpg,None,"Card tích hợp, - Intel Graphics",16 GB,DDR5 (1 khe 8 GB onboard + 1 khe 8 GB),...,Full HD (1920 x 1080),45% NTSC,60Hz,"Chống chói Anti Glare, LED Backlit, 250 nits","2 x USB 3.2, 1 x USB 2.0, Jack tai nghe 3.5 mm, 1 x USB 3.2 Gen 1 Type-C, HDMI 1.4",HD 720p,"3-cell Li-ion, 42 Wh",Dài 359.7 mm - Rộng 232.5 mm - Dày 17.9 mm - 1.7 kg,Vỏ nhựa,2025
4,ASUS,362621,https://www.thegioididong.com/laptop/asus-tuf-gaming-fa506ncq-r7-170-hn005w,Asus TUF Gaming FA506NCQ R7 170 (HN005W),23.890.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/362621/asus-tuf-gaming-fa506ncq-r7-170-hn005w-thumb-639059676707947017-600x600.jpg,None,"Card rời, -, NVIDIA GeForce RTX 3050, 4 GB",16 GB,DDR5 (1 khe 16 GB + 1 khe rời),...,Full HD (1920 x 1080),"62.5% sRGB, 47.34% Adobe RGB, 45% NTSC",144Hz,"Chống chói Anti Glare, Adaptive-Sync, 250 nits","Jack tai nghe 3.5 mm, 1 x USB 3.2 Gen 2 Type-C (Hỗ trợ DisplayPort), 3 x USB 3.2, LAN (RJ45)",HD webcam,"3-cell Li-ion, 48 Wh",Dài 359 mm - Rộng 256 mm - Dày 24.5 mm - 2.3 kg,Vỏ nhựa,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,GIGABYTE,341751,https://www.thegioididong.com/laptop/gigabyte-a16-ga6h-i5-13420h-gaming-a16-cthh3vn893sh,GIGABYTE Gaming A16 GA6H i5 13420H (GAMING-A16-CTHH3VN893SH),30.090.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/341751/gigabyte-a16-ga6h-i5-13420h-gaming-a16-cthh3vn893sh-thumb-638899248610359665-600x600.jpg,None,"Card rời, - NVIDIA GeForce RTX 5050, 8 GB",16 GB,DDR5 (1 khe 16 GB + 1 khe rời),...,WUXGA (1920 x 1200),45% NTSC,165 Hz,"Chống chói Anti Glare, 300 nits","1 x USB 2.0, Jack tai nghe 3.5 mm, 1 x USB Type-C 3.2 (hỗ trợ DisplayPort 1.4 và Power delivery 3.0), 2 x USB 3.2, LAN (RJ45), HDMI 2.1",HD webcam,"Li-Polymer, 76Wh",Dài 358.3 mm - Rộng 262.5 mm - Dày 22.99 mm - 2.227 kg,Vỏ nhựa,2025
438,GIGABYTE,341750,https://www.thegioididong.com/laptop/gigabyte-aero-x16-r7-ai-350-gigabyte-aero-x161vh93vnc64ah,GIGABYTE Gaming AERO X16 R7 AI 350 (GIGABYTE-AERO-X161VH93VNC64AH),44.090.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/341750/gigabyte-aero-x16-r7-ai-350-gigabyte-aero-x161vh93vnc64ah-thumb-638899250698522537-600x600.jpg,None,"Card rời, - NVIDIA GeForce RTX 5060, 8 GB",32 GB,DDR5 (1 khe 16 GB + 1 khe 16 GB),...,WQXGA (2560 x 1600),100% sRGB,165 Hz,400 nits,"1 x USB 2.0, Jack tai nghe 3.5 mm, 1 x USB Type-C (hỗ trợ USB 4, DisplayPort 1.4 và Power Delivery 3.0), 2 x USB 3.2, LAN (RJ45), HDMI 2.1","FHD 1080p, Camera IR","Li-Polymer, 76Wh",Dài 355 mm - Rộng 250.7 mm - Dày 19.99 mm - 1.99 kg,Vỏ bằng kim loại - Chiếu nghỉ tay bằng nhựa,2025
439,GIGABYTE,334694,https://www.thegioididong.com/laptop/gigabyte-aorus-16x-x6lag-i7-9rx6lasgddjixdvn010,GIGABYTE Gaming AORUS 16X X6LAG i7 14650HX (9RX6LASGDDJIXDVN010),36.290.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/334694/gigabyte-aorus-16x-x6lag-i7-9rx6lasgddjixdvn010-thumb-638828334263331009-600x600.jpg,None,"Card rời, - NVIDIA GeForce RTX 4070, 8 GB",16 GB,DDR5 (1 khe 8 GB + 1 khe 8 GB),...,WQXGA (2560 x 1600),100% sRGB,165 Hz,"Chống chói Anti Glare, 400 nits","2 x USB 3.2, HDMI, 1 x USB Type-C (hỗ trợ DisplayPort), 1 x Thunderbolt 4 (hỗ trợ display/power delivery), 1 x Headphone/microphone combo, LAN (RJ45)",HD webcam,"4-cell Li-ion, 99 Wh",Dài 356 mm - Rộng 254 mm - Dày 27 mm - 2.345 kg,Vỏ nhựa,2024
440,GIGABYTE,359928,https://www.thegioididong.com/laptop/gigabyte-gaming-a16-ga6h-i7-13620h-cwhi3vnc94sh,GIGABYTE Gaming A16 GA6H i7 13620H (CWHI3VNC94SH),40.790.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/359928/gigabyte-gaming-a16-ga6h-i7-13620h-cthi3vn893sh-thumb-639003672081449517-600x600.jpg,None,"Card rời, - NVIDIA GeForce RTX 5070, 8 GB",16 GB,DDR5 (1 khe 16 GB + 1 khe rời),...,WQXGA (2560 x 1600),100% sRGB,165 Hz,"Chống chói Anti Glare, 400 nits","2 x USB 3.2, 1 x USB 2.0, 1 x Headphone/ Microphone combo audio jack, LAN (RJ45), HDMI 2.1, 1 x USB 3.2 Gen 1 Type-C (hỗ trợ Power Delivery, DisplayPort)","FHD Webcam, IR camera","4-cell Li-Polymer, 76.1 Wh",Dài 358.3 mm - Rộng 262.5 mm - Dày 22.99 mm - 2.268 kg,Vỏ nhựa,2025
441,GIGABYTE,343047,https://www.thegioididong.com/laptop/gigabyte-gaming-aero-x16-r7-ai-350-gigabyte-aero-x16-1vh93vnc94dh,GIGABYTE Gaming AERO X16 R7 AI 350 (GIGABYTE-AERO-X16-1VH93VNC94DH),41.290.000₫,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/343047/gigabyte-gaming-aero-x16-r7-ai-350-gigabyte-aero-x16-1vh93vnc94dh-thumb-3-639015736786351175-600x600.jpg,None,"Card rời, - NVIDIA GeForce RTX 5060, 8 GB",16 GB,DDR5 (1 khe 16 GB + 1 khe rời),...,WQXGA (2560 x 1600),100% sRGB,165 Hz,"MUX Switch, 400 nits","Jack tai nghe 3.5 mm, 2 x USB-A (hỗ trợ USB 3.2 Gen 1), 1 x USB-C (USB4 hỗ trợ DisplayPort™ 1.4 và Power Delivery 3.0), 1 x USB-A (hỗ trợ USB 2.0), LAN (RJ45), HDMI 2.1",FHD 1080P + IR Camera for Windows Hello,"4-cell Li-Polymer, 76.1 Wh",Dài 355 mm - Rộng 250.7 mm - Dày 19.99 mm - 1.985 kg,Nắp lưng và mặt đáy bằng kim loại,2025

In [258]:
df.isnull().sum()

brand                       0
id                          0
url_product                 4
name_product                4
price                       7
img_product                 4
cpu_name                  442
gpu                         4
ram_info                    4
ram_type                    4
max_ram_upgrade             4
storage_capacity            4
display_size                4
panel_type                 70
resolution                  4
color_gamut                34
refresh_rate                4
display_technology         15
port                        4
webcam                      4
battery_specifications      4
physical_dimensions         4
material                    4
release_year               11
dtype: int64

In [259]:
null_samples = df[df["name_product"].isnull()]
df = df.drop(null_samples.index)

In [260]:
df['ram_info'].value_counts()

ram_info
16 GB                                             324
32 GB                                              73
8 GB                                               18
24 GB                                              15
64 GB                                               4
128 GB                                              2
16 GB (Nguyên bản 8GB, được nâng cấp thêm 8GB)      1
192 GB                                              1
Name: count, dtype: int64

In [261]:
null_price_samples  = df[df["price"].isnull()]
# df = df.drop(null_samples.index)
null_price_samples

,brand,id,url_product,name_product,price,img_product,cpu_name,gpu,ram_info,ram_type,...,resolution,color_gamut,refresh_rate,display_technology,port,webcam,battery_specifications,physical_dimensions,material,release_year
169,DELL,361534,https://www.thegioididong.com/laptop/dell-14-premium-da14250-ultra-7-255h-71083616,Dell 14 Premium DA14250 Ultra 7 255H (71083616),None,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/361534/dell-14-premium-da14250-ultra-7-255h-71083616-thumb-639036537729959446-600x600.jpg,None,"Card rời, - NVIDIA GeForce RTX 4050, 6 GB",32 GB,LPDDR5X (Onboard),...,3.2K (3200 x 2000) OLED,100% DCI-P3,120Hz,"Anti-Reflective, Eyesafe, Chống bám vân tay và bụi bẩn, Dolby Vision, 400 nits","Jack tai nghe 3.5 mm, 3 x Thunderbolt 4 with USB Type-C (hỗ trợ USB Power Delivery 3.1, DisplayPort 2.1)","FHD Webcam, IR camera","6-cell Li-Po, 69.5 Wh",Dài 320 mm - Rộng 215.97 mm - Dày 18.02 mm - 1.83 kg,Vỏ nhựa,2025
170,DELL,361535,https://www.thegioididong.com/laptop/dell-14-dc14255-r7-ai-350-71083617,Dell 14 DC14255 R7 AI 350 (71083617),None,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/361535/dell-14-dc14255-r7-ai-350-71083617-thumb-639036549700189455-600x600.jpg,None,"Card tích hợp, - AMD Radeon Graphics",16 GB,DDR5 (1 khe 16 GB onboard + 1 khe rời),...,Full HD+ (1920 x 1200),Hãng không công bố,60Hz,"Chống chói Anti Glare, 300 nits","2 x USB 3.2, Jack tai nghe 3.5 mm, 1 x USB 3.2 Gen 2 Type-C (hỗ trợ DisplayPort 1.4 và Power Delivery), HDMI 1.4",HD webcam,"4-cell Li-Po, 54 Wh",Dài 314 mm - Rộng 226.15 mm - Dày 19.9 mm - 1.69 kg,Vỏ nhựa,2025
171,DELL,361537,https://www.thegioididong.com/laptop/dell-inspiron-14-5441-x1-26-100-71069158,Dell Inspiron 14 5441 X1 26 100 (71069158),None,https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/361537/dell-inspiron-14-5441-x1-26-100-71069158-thumb-639036594431939344-600x600.jpg,None,"Card tích hợp, - Qualcomm Adreno GPU",16 GB,LPDDR5X (Onboard),...,Full HD+ (1920 x 1200),Hãng không công bố,60Hz,300 nits,"1 x USB 3.2, 2 x USB4 Type-C (hỗ trợ truyền dữ liệu, DisplayPort, Power Delivery), 1 x Headphone/ Microphone combo audio jack","FHD Webcam, IR camera","3-cell Li-Po, 54 Wh",Dài 314 mm - Rộng 223.75 mm - Dày 17.9 mm - 1.54 kg,Vỏ nhựa,2025

In [262]:
null_price_samples  = df[df["price"].isnull()]
df = df.drop(null_price_samples.index)

### extract_ram

In [263]:
df['ram_info'].value_counts()

ram_info
16 GB                                             322
32 GB                                              72
8 GB                                               18
24 GB                                              15
64 GB                                               4
128 GB                                              2
16 GB (Nguyên bản 8GB, được nâng cấp thêm 8GB)      1
192 GB                                              1
Name: count, dtype: int64

In [264]:
# df.isnull().sum()
def extract_max_update_ram(ram_str):
    if ram_str and isinstance(ram_str, str):
        match = re.search(r'\d+', ram_str)
        if match:
            return int(match.group())
    return None 
df['max_ram_upgrade'] = df['max_ram_upgrade'].apply(extract_max_update_ram)

df['max_ram_upgrade'].value_counts()

max_ram_upgrade
32.0     130
64.0      80
16.0      76
96.0      30
24.0      29
56.0       2
192.0      2
128.0      2
8.0        1
40.0       1
Name: count, dtype: int64

## Extract max_ram_upgrade

In [265]:
def extract_ram(max_ram):
    match = re.search(r'\d+', max_ram)
    return int(match.group())
df['ram_info'] = df['ram_info'].apply(extract_ram)
df['ram_info'].value_counts()

ram_info
16     323
32      72
8       18
24      15
64       4
128      2
192      1
Name: count, dtype: int64

### Extract Price:

In [266]:
def extract_price(price_str):
    match = re.findall(r'\d+', price_str)
    return int(''.join(match))
df['price'] = df['price'].apply(extract_price)
df['price'].head(10)

0    14390000
1    12990000
2    19690000
3    22390000
4    23890000
5    17490000
6    20390000
7    20590000
8    19890000
9    22490000
Name: price, dtype: int64

### clean refresh_rate

In [267]:
df['refresh_rate'].value_counts()

refresh_rate
60Hz                  166
120Hz                  84
144Hz                  58
Hãng không công bố     53
165 Hz                 44
240Hz                  13
180 Hz                 12
48 - 120 Hz             1
30 - 120 Hz             1
60 - 120 Hz             1
90 Hz                   1
250 Hz                  1
Name: count, dtype: int64

In [268]:
def extract_refresh_rate(x):
    x = str(x).lower()
    
    if x == "hãng không công bố" :
        return None
    nums = re.findall(r'\d+', x)
    nums = list(map(int, nums))
    return max(nums)
df['refresh_rate'] = df['refresh_rate'].apply(extract_refresh_rate)
df['refresh_rate'].value_counts().sum()

382

### clean release_year

In [269]:
def extract_release_year(year_str):
    if pd.isna(year_str):
        return None
    year = str(year_str)
    return int(year)
df['release_year'] = df['release_year'].apply(extract_release_year)

In [270]:
df['material'].value_counts()

material
Vỏ nhựa                                                                      229
Vỏ nhựa - nắp lưng bằng kim loại                                              54
Vỏ kim loại                                                                   43
Vỏ nhôm                                                                       22
Vỏ kim loại - Nhôm                                                            21
Vỏ nhựa - Nắp lưng bằng nhôm                                                  13
Vỏ bằng kim loại - Chiếu nghỉ tay bằng nhựa                                    7
Nắp lưng và chiếu nghỉ tay bằng kim loại                                       6
Vỏ hợp kim Nhôm                                                                6
Vỏ nhựa - nắp lưng bằng hợp kim nhôm                                           5
Vỏ kim loại - Nắp lưng bằng nhựa                                               4
Nắp lưng và mặt đáy bằng nhôm                                                  4
Vỏ nhôm - chiếu nghỉ tay bằng nhựa                                             3
Nắp lưng và chiếu nghỉ tay bằng nhôm                                           2
Mặt lưng sợi carbon                                                            2
Mặt lưng Carbon - Chiếu nghỉ tay bằng nhựa                                     2
Mặt lưng nhôm - Chiếu nghỉ tay bằng nhựa                                       2
Vỏ nhựa - chiếu nghỉ tay bằng kim loại                                         2
Vỏ nhôm - Nắp lưng bằng nhựa                                                   2
Mặt lưng nhôm - Mặt dưới nhựa                                                  1
Hợp kim Nhôm-Carbon                                                            1
Mặt lưng kim loại và sợi carbon - Chiếu nghỉ tay bằng nhựa phủ soft-touch      1
Mặt lưng sợi carbon - Chiếu nghỉ tay bằng hợp kim magiê                        1
Nhôm - Magie                                                                   1
Nắp lưng và mặt đáy bằng kim loại                                              1
Name: count, dtype: int64

In [271]:
df['material'].count()

435

### material

In [272]:
def clean_material(material_str):
    material_str = material_str.lower()
    if "nhựa" in material_str:
        return "plastic"
    elif "kim loại" in material_str or "nhôm" in material_str or "magie" in material_str:
        return "metal"
    elif "carbon" in material_str:
        return "carbon"
    else:
        return "other"

df['material'] = df['material'].apply(clean_material)

In [273]:
df['ram_type'].value_counts()

ram_type
DDR5 (1 khe 16 GB + 1 khe rời)             98
LPDDR5X (Onboard)                          69
DDR5 (1 khe 8 GB + 1 khe 8 GB)             46
DDR4 (1 khe 8 GB + 1 khe 8 GB)             40
LPDDR5 (Onboard)                           26
DDR4 (1 khe 16 GB + 1 khe rời)             26
DDR5 (1 khe 16 GB + 1 khe 16 GB)           25
DDR4 (8 GB onboard + 1 khe 8 GB)           14
DDR5 (1 khe 8 GB onboard + 1 khe 8 GB)     14
DDR5 (1 khe 16 GB onboard + 1 khe rời)     14
DDR4 (1 khe 8 GB + 1 khe rời)               7
DDR5 (mỗi khe 16 GB)                        6
DDR5 (1 khe RAM)                            6
DDR4 (Onboard)                              5
DDR5 (1 khe 8 GB onboard + 1 khe 16 GB)     5
DDR5 (1 khe 12 GB + 1 khe 12 GB)            5
DDR5 (1 khe 24 GB + 1 khe trống)            4
DDR5 (1 khe 8 GB + 1 khe trống)             4
DDR4                                        3
DDR4 (1 khe 8 GB onboard + 1 khe trống)     3
DDR5 (1 khe 32 GB + 1 khe 32 GB)            3
DDR5 (Onboard)                              3
DDR4 (1 khe)                                2
LPDDR4X (Onboard)                           2
DDR5 (1 khe 12 GB + 1 khe rời)              1
DDR4 (1 khe 16 GB onboard + 1 khe rời)      1
DDR5 (mỗi khe 48 GB)                        1
DDR5 (1 khe 32 GB + 1 khe trống)            1
LPDDR5 (1 khe onboard)                      1
Name: count, dtype: int64

### CPU name

In this step, I want to extract cpu name from name products by regex

In [274]:
df['name_product'].sample(n= 50)

122                                                    Dell 15 DC15250 i7 1355U (71073959)
20                                         Asus Vivobook 16 A1607CA Ultra 5 225H (MB038WS)
39                                            Asus Zenbook 14 UM3406GA R7 AI 445 (QD075WS)
334                              Acer Aspire Lite 15 AL15 42P R50R R5 7430U (NX.D34SV.004)
314                                        Lenovo ThinkBook 14 G8 Core 7 240H (21SG007UVN)
423                                         MSI Prestige 13 AI+ A2VMG Ultra 7 258V (040VN)
196                                                          HP 245 G10 R5 7530U (A20TDPT)
130                                             Dell 16 Plus DB16250 Ultra 7 256V (X65NW7)
437                           GIGABYTE Gaming A16 GA6H i5 13420H (GAMING-A16-CTHH3VN893SH)
357                           Acer Gaming Aspire 5 A515 58GM 51LB i5 13420H (NX.KQ4SV.002)
231                                                  HP Probook 450 G10 i5 1335U (9H1N5PT)
35                                       Asus Zenbook S 14 UX5406SA Ultra 7 258V (PV140WS)
201                                    HP OmniBook 5 AI 16 af1048TU Ultra 5 225U (BZ7Q9PA)
161                                                Dell 14 DC14255 R5 AI 330 (DC4AI5278W1)
368    Acer Aspire Go 14 AG14-72P-54DF Core 5 120U (NX.JSBSV.009)\n                Mẫu mới
245                                                   HP 15 fd1037TU Core 7 150U (9Z2W5PA)
214                                             HP Pavilion 15 eg3093TU i5 1335U (8C5L4PA)
327        Lenovo Ideapad Slim 5 OLED 14AGP11 R7 445 (83S1003FVN)\n                Mẫu mới
8                                      Asus Gaming Vivobook 16X K3605VC i5 13420H (RP364W)
261                                   Lenovo IdeaPad Slim 3 15IRH10 i5 13420H (83K1000HVN)
56                 Asus VivoBook 16 X1607CA Ultra 5 225H (MB980W)\n                Mẫu mới
282                                           Lenovo ThinkBook 14 Core 7 240H (21SG007VVN)
292                                        Lenovo Gaming LOQ 15ARP9 R7 7435HS (83JC00J0VN)
22                                           Asus Vivobook 14 X1404VA Core 5 120U (EB155W)
365                              Acer Aspire Lite 15 AL15 42P R08M R7 7730U (NX.D3QSV.001)
362                           Acer Gaming Aspire 5 A515 58GM 53PZ i5 13420H (NX.KQ4SV.008)
215                                                   HP 15 fd1039TU Core 7 150U (9Z2W7PA)
338                             Acer Aspire Lite 15 AL15 71P 517D i5 12450H (NX.J7KSV.001)
146                                              Dell Inspiron 15 3520 i7 1255U (71053682)
49                                            Asus Zenbook UX3405CA Ultra 7 255H (PZ188WS)
68                                              Asus Vivobook Go 15 E1504FA R5 40 (BQ350W)
158                                                  Dell XPS 13 9350 Ultra 7 258V (PP9H1)
370                                   Acer Aspire 5 A515 58M 79R7 i7 13620H (NX.KQ8SV.007)
15                                            Asus Gaming V16 V3607VU Core 5 210H (RP192W)
72                                          Asus Zenbook S 16 UM5606GA R9 AI 465 (SS384WS)
208                                                      HP 15 fd0235TU i5 1334U (9Q970PA)
387       Acer Gaming Predator Helios Neo 16 AI PHN16 73 757W Ultra 7 255HX (NH.QVQSV.001)
294                                        Lenovo ThinkBook 14 G8 Core 5 210H (21SG007SVN)
358                             Acer Aspire Lite 14 AL14 71P 55P9 i5 13500H (NX.D7USV.001)
347                             Acer Gaming Nitro V ANV15 51 55CA i5 13420H (NH.QN8SV.004)
105                                      Dell Latitude 3450 i5 1335U (L3450-1335U-16512WN)
137                                              Dell Inspiron 15 3530 i5 1334U (71043885)
254                                 HP Gaming OMEN Max 16 ah0213TX Ultra 9 275HX (C1WR2PA)
157                                          Dell Inspiron 14 5441 X1P 64 100 (N4O10441W1)
6                                           Asus Vivobook S14 S3407VA Core 5 210H (LY146W)
3                                            Asus Vivobook 15 X1504VA Core 7 150U (BQ295W)
223                                   HP OmniBook 5 Flip 14 fp0055TU Core 7 150U (BZ7Q4PA)
418                                      MSI Gaming Katana 15 HX B14WFK i7 14650HX (267VN)
309                                          Lenovo Gaming LOQ 15AHP10 R7 250 (83JG0047VN)
93                                                   Dell 15 DC15250 i5 1334U (DC5I5357W1)
Name: name_product, dtype: object

In [275]:
pattern = r'\b(i\d\s*\d+[A-Z]*|Core\s*\d+\s*\d+[A-Z]*|Ultra\s*\d+\s*\d+[A-Z]*|R\d\s*(?:AI\s*)?\d+[A-Z]*)\b'
def extract_cpu(name_product):
    match = re.search(pattern, name_product)
    return match.group() if match else None

df['cpu_name'] = df['name_product'].apply(extract_cpu)

In [276]:
df["cpu_name"].value_counts()

cpu_name
i5 13420H       27
i5 1334U        25
i7 1355U        24
Core 5 120U     23
i7 13620H       21
                ..
Ultra 7 268V     1
R5 8640U         1
R5 220           1
R7 7730U         1
Ultra 7 355      1
Name: count, Length: 87, dtype: int64

check products with null cpu name

In [277]:
df['cpu_name'].isna().sum()

19

In [278]:
def extract_cpu_fix(name):
    patterns = [
    r'X1[PE]?\s\d+\s\d+',        # Snapdragon X1, X1P
    r'R\d\s*AI\s*\d+',          # Ryzen AI HX series
    r'RYZEN\s*AI.*?\d+',        # RYZEN AI Special
    r'N\d+',                    # Intel N-series
    r'U\d+\s*\d+[A-Z]*',        # another ultra series
    r'UX?9\s*\d+H'              # # Ultra 9 followed by MSI
]
    for p in patterns:
        match = re.search(p, name, re.IGNORECASE)
        if match:
            return match.group()
    return None

df['cpu_name'] = df['cpu_name'].fillna(
    df['name_product'].apply(extract_cpu_fix)
)

#check by select random 30 samples

In [279]:
df['cpu_name'].sample(n = 30)

206        i5 13420H
44       Core 5 210H
226     Ultra 7 255H
124         i7 1355U
84        i5 13450HX
405        i7 13620H
147         i7 1255U
94          R5 7530U
176         i5 1334U
196         R5 7530U
304      Core 7 240H
215      Core 7 150U
385    Ultra 9 275HX
336         R5 6600H
27      Ultra 9 285H
354         i3 1305U
422     Ultra 9 288V
92          i5 1334U
256             None
301           R7 260
355         i5 1334U
437        i5 13420H
249        X1 26 100
366        i7 13620H
287        i5 13420H
50       Core 5 210H
359        R5 7535HS
68             R5 40
209        R7 8840HS
378     Ultra 5 226V
Name: cpu_name, dtype: object

### clean physical_dimensions

In [280]:
# df['physical_dimensions'].sample(n= 50)
# In this stage, I will seperate it into 3 columns in order to filter easier
pattern_lengths_mn = r"[Dd]ài\s*(\d+\.?\d*)"
pattern_width_mn = r"[Rr]ộng\s*(\d+\.?\d*)"
pattern_thickness_mn = r"[Dd]ày\s*(\d+\.?\d*)"
pattern_weight_kg = r"(\d+\.?\d*) kg"
df['length_mm'] = df['physical_dimensions'].str.extract(pattern_lengths_mn, expand=False)
df['width_mm']  = df['physical_dimensions'].str.extract(pattern_width_mn, expand=False)
df['depth_mm']  = df['physical_dimensions'].str.extract(pattern_thickness_mn, expand=False)
df['weight_kg'] = df['physical_dimensions'].str.extract(pattern_weight_kg, expand=False)
cols = ['length_mm', 'width_mm', 'depth_mm', 'weight_kg']


for col in cols:
    df[col] = df[col].astype(float)

In [281]:
df[cols]

     length_mm  width_mm  depth_mm  weight_kg
0        360.3     232.5     17.90      1.630
1        359.7     232.5     17.90      1.700
2        359.7     232.5     17.90      1.700
3        359.7     232.5     17.90      1.700
4        359.0     256.0     24.50      2.300
..         ...       ...       ...        ...
437      358.3     262.5     22.99      2.227
438      355.0     250.7     19.99      1.990
439      356.0     254.0     27.00      2.345
440      358.3     262.5     22.99      2.268
441      355.0     250.7     19.99      1.985

[435 rows x 4 columns]

## GPU clean

In [282]:
df["gpu"].value_counts()

gpu
Card tích hợp, - Intel Graphics                                                          77
Card tích hợp, -, Intel UHD Graphics                                                     62
Card tích hợp, -, Intel Iris Xe Graphics                                                 39
Card tích hợp, - AMD Radeon Graphics                                                     35
Card tích hợp, - Intel Arc Graphics                                                      28
Card rời, - NVIDIA GeForce RTX 5060, 8 GB                                                25
Card rời, - NVIDIA GeForce RTX 4050, 6 GB                                                24
Card rời, - NVIDIA GeForce RTX 3050, 6 GB                                                23
Card rời, - NVIDIA GeForce RTX 5050, 8 GB                                                23
Card tích hợp, - Intel Arc 140V                                                          11
Card rời, - NVIDIA GeForce RTX 5070, 8 GB                                                11
Card tích hợp, - Qualcomm Adreno GPU                                                      8
Card rời, -, NVIDIA GeForce RTX 3050, 4 GB                                                7
Card tích hợp, - Intel Arc Graphics 130V                                                  6
Card rời, - NVIDIA GeForce RTX 2050, 4 GB                                                 5
Card tích hợp, - Intel UHD Graphics (Iris Xe Graphics chỉ hoạt động với RAM kênh đôi)     4
Card rời, - NVIDIA GeForce RTX 5080, 16 GB                                                4
Card tích hợp, - AMD Radeon 840M                                                          3
Card rời, - NVIDIA GeForce RTX 4060, 8 GB                                                 3
Card tích hợp, - AMD Radeon 840M Graphics                                                 3
Card tích hợp, - Intel Iris Xe Graphics eligible                                          3
Card rời, - NVIDIA Geforce MX570A, 2 GB                                                   3
Card tích hợp, - Intel Arc 140T                                                           3
Card tích hợp, - AMD Radeon 660M Graphics                                                 2
Card rời, - NVIDIA GeForce RTX 4070, 8 GB                                                 2
Card tích hợp, - AMD Radeon 680M Graphics                                                 2
Card rời, - NVIDIA GeForce RTX 5090, 24 GB                                                2
Card tích hợp, - AMD Radeon 610M Graphics                                                 2
Card tích hợp, - AMD Radeon 860M Graphics                                                 2
Card tích hợp, - AMD Radeon 8060S Graphics                                                2
Card tích hợp, - AMD Radeon 890M Graphics                                                 1
Card tích hợp, - Intel UHD XE                                                             1
Card tích hợp, -, Integrated Graphics                                                     1
Card tích hợp, - AMD Radeon 820M Graphics                                                 1
Card tích hợp, - NVIDIA GeForce RTX 5060, 8 GB                                            1
Card tích hợp, - Intel Arc Graphics 140V                                                  1
Card rời, - NVIDIA GeForce RTX 5050, 8 GB - GDDR7                                         1
Card rời, - NVIDIA GeForce RTX 5070Ti, 12 GB                                              1
Card tích hợp, - AMD Radeon 880M                                                          1
Card rời, - NVIDIA GeForce RTX 5070                                                       1
Card rời, - NVIDIA GeForce RTX 5060                                                       1
Name: count, dtype: int64

In [283]:

def extract_gpu_name(text):
    if not isinstance(text, str):
        return None

    text = re.sub(r"\(.*?\)", "", text)
    # base on some sign -, ,- to normalize
    text = text.replace("-,", "-").replace(", -", "-")
    # after this steps: normalize will into Card tích hợc-AMD Radeon 820M Graphics
    #or Card rời-NVIDIA GeForce RTX 5060, 8 GB
    if "-" in text:
        #ex: Card tích hợc-AMD Radeon 820M Graphics
        part = text.split("-")[-1]
    # remove vram ex 8GB,...
    part = re.sub(r"\d+\s*GB.*", "", part)

    # clean the rest of noise (remnove ,)
    name = part.strip(" ,-")
    return name if name else None

In [284]:
df['gpu_type'] = df['gpu'].str.extract(r'(tích hợp|rời)', expand=False)
df['gpu_ram'] = df['gpu'].str.extract(r'(\d+)\s*GB')[0].astype(float)

df["gpu_name"] = df["gpu"].apply(extract_gpu_name)
df["gpu_name"].isna().sum()
df["gpu_name"].sample(n =50 )

355    Intel Iris Xe Graphics eligible
162            Intel Arc Graphics 130V
71             NVIDIA GeForce RTX 5060
202                     Intel Graphics
352            NVIDIA GeForce RTX 5050
391             Intel Iris Xe Graphics
266           AMD Radeon 660M Graphics
254            NVIDIA GeForce RTX 5080
430            NVIDIA GeForce RTX 5070
223                     Intel Graphics
137             Intel Iris Xe Graphics
331                              GDDR7
134             Intel Iris Xe Graphics
237                     Intel Graphics
351    Intel Iris Xe Graphics eligible
204                AMD Radeon Graphics
272           AMD Radeon 680M Graphics
190                     Intel Graphics
12                  Intel UHD Graphics
148             Intel Iris Xe Graphics
173              NVIDIA Geforce MX570A
150                 Intel UHD Graphics
139            NVIDIA GeForce RTX 5060
184                AMD Radeon Graphics
252                     Intel Graphics
0                  AMD Radeon Graphics
207                     Intel Graphics
382            NVIDIA GeForce RTX 4050
37                  Intel Arc Graphics
368                 Intel UHD Graphics
220                     Intel Graphics
23                  Intel Arc Graphics
431            NVIDIA GeForce RTX 5060
67             NVIDIA GeForce RTX 5050
34                 AMD Radeon Graphics
249                Qualcomm Adreno GPU
236                    AMD Radeon 840M
8              NVIDIA GeForce RTX 3050
319           AMD Radeon 660M Graphics
48                 AMD Radeon Graphics
250           AMD Radeon 890M Graphics
235                     Intel Graphics
194                 Intel UHD Graphics
253                     Intel Graphics
109             Intel Iris Xe Graphics
107             Intel Iris Xe Graphics
128             Intel Iris Xe Graphics
25             NVIDIA GeForce RTX 5050
159            NVIDIA GeForce RTX 5070
6                   Intel UHD Graphics
Name: gpu_name, dtype: object

In [285]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 435 entries, 0 to 441
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   brand                   435 non-null    object
 1   id                      435 non-null    object
 2   url_product             435 non-null    object
 3   name_product            435 non-null    object
 4   price                   435 non-null    int64
 5   img_product             435 non-null    object
 6   cpu_name                430 non-null    object
 7   gpu                     435 non-null    object
 8   ram_info                435 non-null    int64
 9   ram_type                435 non-null    object
 10  max_ram_upgrade         353 non-null    float64
 11  storage_capacity        435 non-null    object
 12  display_size            435 non-null    object
 13  panel_type              369 non-null    object
 14  resolution              435 non-null    object
 15  color_gamut             405 non-null    object
 16  refresh_rate            382 non-null    float64
 17  display_technology      424 non-null    object
 18  port                    435 non-null    object
 19  webcam                  435 non-null    object
 20  battery_specifications  435 non-null    object
 21  physical_dimensions     435 non-null    object
 22  material                435 non-null    object
 23  release_year            428 non-null    float64
 24  length_mm               435 non-null    float64
 25  width_mm                435 non-null    float64
 26  depth_mm                434 non-null    float64
 27  weight_kg               435 non-null    float64
 28  gpu_type                435 non-null    object
 29  gpu_ram                 135 non-null    float64
 30  gpu_name                435 non-null    object
dtypes: float64(8), int64(2), object(21)
memory usage: 108.8+ KB

## Push to mongoDB with new collection: laptop_cleaned

In [286]:
clean_collection = db["laptop_cleaned"]
data = df.to_dict(orient='records')
clean_collection.insert_many(data)

InsertManyResult([ObjectId('69e63737b2c98212b735f561'), ObjectId('69e63737b2c98212b735f562'), ObjectId('69e63737b2c98212b735f563'), ObjectId('69e63737b2c98212b735f564'), ObjectId('69e63737b2c98212b735f565'), ObjectId('69e63737b2c98212b735f566'), ObjectId('69e63737b2c98212b735f567'), ObjectId('69e63737b2c98212b735f568'), ObjectId('69e63737b2c98212b735f569'), ObjectId('69e63737b2c98212b735f56a'), ObjectId('69e63737b2c98212b735f56b'), ObjectId('69e63737b2c98212b735f56c'), ObjectId('69e63737b2c98212b735f56d'), ObjectId('69e63737b2c98212b735f56e'), ObjectId('69e63737b2c98212b735f56f'), ObjectId('69e63737b2c98212b735f570'), ObjectId('69e63737b2c98212b735f571'), ObjectId('69e63737b2c98212b735f572'), ObjectId('69e63737b2c98212b735f573'), ObjectId('69e63737b2c98212b735f574'), ObjectId('69e63737b2c98212b735f575'), ObjectId('69e63737b2c98212b735f576'), ObjectId('69e63737b2c98212b735f577'), ObjectId('69e63737b2c98212b735f578'), ObjectId('69e63737b2c98212b735f579'), ObjectId('69e63737b2c98212b735f57a'), ObjectId('69e63737b2c98212b735f57b'), ObjectId('69e63737b2c98212b735f57c'), ObjectId('69e63737b2c98212b735f57d'), ObjectId('69e63737b2c98212b735f57e'), ObjectId('69e63737b2c98212b735f57f'), ObjectId('69e63737b2c98212b735f580'), ObjectId('69e63737b2c98212b735f581'), ObjectId('69e63737b2c98212b735f582'), ObjectId('69e63737b2c98212b735f583'), ObjectId('69e63737b2c98212b735f584'), ObjectId('69e63737b2c98212b735f585'), ObjectId('69e63737b2c98212b735f586'), ObjectId('69e63737b2c98212b735f587'), ObjectId('69e63737b2c98212b735f588'), ObjectId('69e63737b2c98212b735f589'), ObjectId('69e63737b2c98212b735f58a'), ObjectId('69e63737b2c98212b735f58b'), ObjectId('69e63737b2c98212b735f58c'), ObjectId('69e63737b2c98212b735f58d'), ObjectId('69e63737b2c98212b735f58e'), ObjectId('69e63737b2c98212b735f58f'), ObjectId('69e63737b2c98212b735f590'), ObjectId('69e63737b2c98212b735f591'), ObjectId('69e63737b2c98212b735f592'), ObjectId('69e63737b2c98212b735f593'), ObjectId('69e63737b2c98212b735f594'), ObjectId('69e63737b2c98212b735f595'), ObjectId('69e63737b2c98212b735f596'), ObjectId('69e63737b2c98212b735f597'), ObjectId('69e63737b2c98212b735f598'), ObjectId('69e63737b2c98212b735f599'), ObjectId('69e63737b2c98212b735f59a'), ObjectId('69e63737b2c98212b735f59b'), ObjectId('69e63737b2c98212b735f59c'), ObjectId('69e63737b2c98212b735f59d'), ObjectId('69e63737b2c98212b735f59e'), ObjectId('69e63737b2c98212b735f59f'), ObjectId('69e63737b2c98212b735f5a0'), ObjectId('69e63737b2c98212b735f5a1'), ObjectId('69e63737b2c98212b735f5a2'), ObjectId('69e63737b2c98212b735f5a3'), ObjectId('69e63737b2c98212b735f5a4'), ObjectId('69e63737b2c98212b735f5a5'), ObjectId('69e63737b2c98212b735f5a6'), ObjectId('69e63737b2c98212b735f5a7'), ObjectId('69e63737b2c98212b735f5a8'), ObjectId('69e63737b2c98212b735f5a9'), ObjectId('69e63737b2c98212b735f5aa'), ObjectId('69e63737b2c98212b735f5ab'), ObjectId('69e63737b2c98212b735f5ac'), ObjectId('69e63737b2c98212b735f5ad'), ObjectId('69e63737b2c98212b735f5ae'), ObjectId('69e63737b2c98212b735f5af'), ObjectId('69e63737b2c98212b735f5b0'), ObjectId('69e63737b2c98212b735f5b1'), ObjectId('69e63737b2c98212b735f5b2'), ObjectId('69e63737b2c98212b735f5b3'), ObjectId('69e63737b2c98212b735f5b4'), ObjectId('69e63737b2c98212b735f5b5'), ObjectId('69e63737b2c98212b735f5b6'), ObjectId('69e63737b2c98212b735f5b7'), ObjectId('69e63737b2c98212b735f5b8'), ObjectId('69e63737b2c98212b735f5b9'), ObjectId('69e63737b2c98212b735f5ba'), ObjectId('69e63737b2c98212b735f5bb'), ObjectId('69e63737b2c98212b735f5bc'), ObjectId('69e63737b2c98212b735f5bd'), ObjectId('69e63737b2c98212b735f5be'), ObjectId('69e63737b2c98212b735f5bf'), ObjectId('69e63737b2c98212b735f5c0'), ObjectId('69e63737b2c98212b735f5c1'), ObjectId('69e63737b2c98212b735f5c2'), ObjectId('69e63737b2c98212b735f5c3'), ObjectId('69e63737b2c98212b735f5c4'), ObjectId('69e63737b2c98212b735f5c5'), ObjectId('69e63737b2c98212b735f5c6'), ObjectId('69e63737b2c98212b735f5c7'), ObjectId('69e63737b2c98212b735f5c8'), ObjectId('69e63737b2c98212b735f5c9'), ObjectId('69e63737b2c98212b735f5ca'), ObjectId('69e63737b2c98212b735f5cb'), ObjectId('69e63737b2c98212b735f5cc'), ObjectId('69e63737b2c98212b735f5cd'), ObjectId('69e63737b2c98212b735f5ce'), ObjectId('69e63737b2c98212b735f5cf'), ObjectId('69e63737b2c98212b735f5d0'), ObjectId('69e63737b2c98212b735f5d1'), ObjectId('69e63737b2c98212b735f5d2'), ObjectId('69e63737b2c98212b735f5d3'), ObjectId('69e63737b2c98212b735f5d4'), ObjectId('69e63737b2c98212b735f5d5'), ObjectId('69e63737b2c98212b735f5d6'), ObjectId('69e63737b2c98212b735f5d7'), ObjectId('69e63737b2c98212b735f5d8'), ObjectId('69e63737b2c98212b735f5d9'), ObjectId('69e63737b2c98212b735f5da'), ObjectId('69e63737b2c98212b735f5db'), ObjectId('69e63737b2c98212b735f5dc'), ObjectId('69e63737b2c98212b735f5dd'), ObjectId('69e63737b2c98212b735f5de'), ObjectId('69e63737b2c98212b735f5df'), ObjectId('69e63737b2c98212b735f5e0'), ObjectId('69e63737b2c98212b735f5e1'), ObjectId('69e63737b2c98212b735f5e2'), ObjectId('69e63737b2c98212b735f5e3'), ObjectId('69e63737b2c98212b735f5e4'), ObjectId('69e63737b2c98212b735f5e5'), ObjectId('69e63737b2c98212b735f5e6'), ObjectId('69e63737b2c98212b735f5e7'), ObjectId('69e63737b2c98212b735f5e8'), ObjectId('69e63737b2c98212b735f5e9'), ObjectId('69e63737b2c98212b735f5ea'), ObjectId('69e63737b2c98212b735f5eb'), ObjectId('69e63737b2c98212b735f5ec'), ObjectId('69e63737b2c98212b735f5ed'), ObjectId('69e63737b2c98212b735f5ee'), ObjectId('69e63737b2c98212b735f5ef'), ObjectId('69e63737b2c98212b735f5f0'), ObjectId('69e63737b2c98212b735f5f1'), ObjectId('69e63737b2c98212b735f5f2'), ObjectId('69e63737b2c98212b735f5f3'), ObjectId('69e63737b2c98212b735f5f4'), ObjectId('69e63737b2c98212b735f5f5'), ObjectId('69e63737b2c98212b735f5f6'), ObjectId('69e63737b2c98212b735f5f7'), ObjectId('69e63737b2c98212b735f5f8'), ObjectId('69e63737b2c98212b735f5f9'), ObjectId('69e63737b2c98212b735f5fa'), ObjectId('69e63737b2c98212b735f5fb'), ObjectId('69e63737b2c98212b735f5fc'), ObjectId('69e63737b2c98212b735f5fd'), ObjectId('69e63737b2c98212b735f5fe'), ObjectId('69e63737b2c98212b735f5ff'), ObjectId('69e63737b2c98212b735f600'), ObjectId('69e63737b2c98212b735f601'), ObjectId('69e63737b2c98212b735f602'), ObjectId('69e63737b2c98212b735f603'), ObjectId('69e63737b2c98212b735f604'), ObjectId('69e63737b2c98212b735f605'), ObjectId('69e63737b2c98212b735f606'), ObjectId('69e63737b2c98212b735f607'), ObjectId('69e63737b2c98212b735f608'), ObjectId('69e63737b2c98212b735f609'), ObjectId('69e63737b2c98212b735f60a'), ObjectId('69e63737b2c98212b735f60b'), ObjectId('69e63737b2c98212b735f60c'), ObjectId('69e63737b2c98212b735f60d'), ObjectId('69e63737b2c98212b735f60e'), ObjectId('69e63737b2c98212b735f60f'), ObjectId('69e63737b2c98212b735f610'), ObjectId('69e63737b2c98212b735f611'), ObjectId('69e63737b2c98212b735f612'), ObjectId('69e63737b2c98212b735f613'), ObjectId('69e63737b2c98212b735f614'), ObjectId('69e63737b2c98212b735f615'), ObjectId('69e63737b2c98212b735f616'), ObjectId('69e63737b2c98212b735f617'), ObjectId('69e63737b2c98212b735f618'), ObjectId('69e63737b2c98212b735f619'), ObjectId('69e63737b2c98212b735f61a'), ObjectId('69e63737b2c98212b735f61b'), ObjectId('69e63737b2c98212b735f61c'), ObjectId('69e63737b2c98212b735f61d'), ObjectId('69e63737b2c98212b735f61e'), ObjectId('69e63737b2c98212b735f61f'), ObjectId('69e63737b2c98212b735f620'), ObjectId('69e63737b2c98212b735f621'), ObjectId('69e63737b2c98212b735f622'), ObjectId('69e63737b2c98212b735f623'), ObjectId('69e63737b2c98212b735f624'), ObjectId('69e63737b2c98212b735f625'), ObjectId('69e63737b2c98212b735f626'), ObjectId('69e63737b2c98212b735f627'), ObjectId('69e63737b2c98212b735f628'), ObjectId('69e63737b2c98212b735f629'), ObjectId('69e63737b2c98212b735f62a'), ObjectId('69e63737b2c98212b735f62b'), ObjectId('69e63737b2c98212b735f62c'), ObjectId('69e63737b2c98212b735f62d'), ObjectId('69e63737b2c98212b735f62e'), ObjectId('69e63737b2c98212b735f62f'), ObjectId('69e63737b2c98212b735f630'), ObjectId('69e63737b2c98212b735f631'), ObjectId('69e63737b2c98212b735f632'), ObjectId('69e63737b2c98212b735f633'), ObjectId('69e63737b2c98212b735f634'), ObjectId('69e63737b2c98212b735f635'), ObjectId('69e63737b2c98212b735f636'), ObjectId('69e63737b2c98212b735f637'), ObjectId('69e63737b2c98212b735f638'), ObjectId('69e63737b2c98212b735f639'), ObjectId('69e63737b2c98212b735f63a'), ObjectId('69e63737b2c98212b735f63b'), ObjectId('69e63737b2c98212b735f63c'), ObjectId('69e63737b2c98212b735f63d'), ObjectId('69e63737b2c98212b735f63e'), ObjectId('69e63737b2c98212b735f63f'), ObjectId('69e63737b2c98212b735f640'), ObjectId('69e63737b2c98212b735f641'), ObjectId('69e63737b2c98212b735f642'), ObjectId('69e63737b2c98212b735f643'), ObjectId('69e63737b2c98212b735f644'), ObjectId('69e63737b2c98212b735f645'), ObjectId('69e63737b2c98212b735f646'), ObjectId('69e63737b2c98212b735f647'), ObjectId('69e63737b2c98212b735f648'), ObjectId('69e63737b2c98212b735f649'), ObjectId('69e63737b2c98212b735f64a'), ObjectId('69e63737b2c98212b735f64b'), ObjectId('69e63737b2c98212b735f64c'), ObjectId('69e63737b2c98212b735f64d'), ObjectId('69e63737b2c98212b735f64e'), ObjectId('69e63737b2c98212b735f64f'), ObjectId('69e63737b2c98212b735f650'), ObjectId('69e63737b2c98212b735f651'), ObjectId('69e63737b2c98212b735f652'), ObjectId('69e63737b2c98212b735f653'), ObjectId('69e63737b2c98212b735f654'), ObjectId('69e63737b2c98212b735f655'), ObjectId('69e63737b2c98212b735f656'), ObjectId('69e63737b2c98212b735f657'), ObjectId('69e63737b2c98212b735f658'), ObjectId('69e63737b2c98212b735f659'), ObjectId('69e63737b2c98212b735f65a'), ObjectId('69e63737b2c98212b735f65b'), ObjectId('69e63737b2c98212b735f65c'), ObjectId('69e63737b2c98212b735f65d'), ObjectId('69e63737b2c98212b735f65e'), ObjectId('69e63737b2c98212b735f65f'), ObjectId('69e63737b2c98212b735f660'), ObjectId('69e63737b2c98212b735f661'), ObjectId('69e63737b2c98212b735f662'), ObjectId('69e63737b2c98212b735f663'), ObjectId('69e63737b2c98212b735f664'), ObjectId('69e63737b2c98212b735f665'), ObjectId('69e63737b2c98212b735f666'), ObjectId('69e63737b2c98212b735f667'), ObjectId('69e63737b2c98212b735f668'), ObjectId('69e63737b2c98212b735f669'), ObjectId('69e63737b2c98212b735f66a'), ObjectId('69e63737b2c98212b735f66b'), ObjectId('69e63737b2c98212b735f66c'), ObjectId('69e63737b2c98212b735f66d'), ObjectId('69e63737b2c98212b735f66e'), ObjectId('69e63737b2c98212b735f66f'), ObjectId('69e63737b2c98212b735f670'), ObjectId('69e63737b2c98212b735f671'), ObjectId('69e63737b2c98212b735f672'), ObjectId('69e63737b2c98212b735f673'), ObjectId('69e63737b2c98212b735f674'), ObjectId('69e63737b2c98212b735f675'), ObjectId('69e63737b2c98212b735f676'), ObjectId('69e63737b2c98212b735f677'), ObjectId('69e63737b2c98212b735f678'), ObjectId('69e63737b2c98212b735f679'), ObjectId('69e63737b2c98212b735f67a'), ObjectId('69e63737b2c98212b735f67b'), ObjectId('69e63737b2c98212b735f67c'), ObjectId('69e63737b2c98212b735f67d'), ObjectId('69e63737b2c98212b735f67e'), ObjectId('69e63737b2c98212b735f67f'), ObjectId('69e63737b2c98212b735f680'), ObjectId('69e63737b2c98212b735f681'), ObjectId('69e63737b2c98212b735f682'), ObjectId('69e63737b2c98212b735f683'), ObjectId('69e63737b2c98212b735f684'), ObjectId('69e63737b2c98212b735f685'), ObjectId('69e63737b2c98212b735f686'), ObjectId('69e63737b2c98212b735f687'), ObjectId('69e63737b2c98212b735f688'), ObjectId('69e63737b2c98212b735f689'), ObjectId('69e63737b2c98212b735f68a'), ObjectId('69e63737b2c98212b735f68b'), ObjectId('69e63737b2c98212b735f68c'), ObjectId('69e63737b2c98212b735f68d'), ObjectId('69e63737b2c98212b735f68e'), ObjectId('69e63737b2c98212b735f68f'), ObjectId('69e63737b2c98212b735f690'), ObjectId('69e63737b2c98212b735f691'), ObjectId('69e63737b2c98212b735f692'), ObjectId('69e63737b2c98212b735f693'), ObjectId('69e63737b2c98212b735f694'), ObjectId('69e63737b2c98212b735f695'), ObjectId('69e63737b2c98212b735f696'), ObjectId('69e63737b2c98212b735f697'), ObjectId('69e63737b2c98212b735f698'), ObjectId('69e63737b2c98212b735f699'), ObjectId('69e63737b2c98212b735f69a'), ObjectId('69e63737b2c98212b735f69b'), ObjectId('69e63737b2c98212b735f69c'), ObjectId('69e63737b2c98212b735f69d'), ObjectId('69e63737b2c98212b735f69e'), ObjectId('69e63737b2c98212b735f69f'), ObjectId('69e63737b2c98212b735f6a0'), ObjectId('69e63737b2c98212b735f6a1'), ObjectId('69e63737b2c98212b735f6a2'), ObjectId('69e63737b2c98212b735f6a3'), ObjectId('69e63737b2c98212b735f6a4'), ObjectId('69e63737b2c98212b735f6a5'), ObjectId('69e63737b2c98212b735f6a6'), ObjectId('69e63737b2c98212b735f6a7'), ObjectId('69e63737b2c98212b735f6a8'), ObjectId('69e63737b2c98212b735f6a9'), ObjectId('69e63737b2c98212b735f6aa'), ObjectId('69e63737b2c98212b735f6ab'), ObjectId('69e63737b2c98212b735f6ac'), ObjectId('69e63737b2c98212b735f6ad'), ObjectId('69e63737b2c98212b735f6ae'), ObjectId('69e63737b2c98212b735f6af'), ObjectId('69e63737b2c98212b735f6b0'), ObjectId('69e63737b2c98212b735f6b1'), ObjectId('69e63737b2c98212b735f6b2'), ObjectId('69e63737b2c98212b735f6b3'), ObjectId('69e63737b2c98212b735f6b4'), ObjectId('69e63737b2c98212b735f6b5'), ObjectId('69e63737b2c98212b735f6b6'), ObjectId('69e63737b2c98212b735f6b7'), ObjectId('69e63737b2c98212b735f6b8'), ObjectId('69e63737b2c98212b735f6b9'), ObjectId('69e63737b2c98212b735f6ba'), ObjectId('69e63737b2c98212b735f6bb'), ObjectId('69e63737b2c98212b735f6bc'), ObjectId('69e63737b2c98212b735f6bd'), ObjectId('69e63737b2c98212b735f6be'), ObjectId('69e63737b2c98212b735f6bf'), ObjectId('69e63737b2c98212b735f6c0'), ObjectId('69e63737b2c98212b735f6c1'), ObjectId('69e63737b2c98212b735f6c2'), ObjectId('69e63737b2c98212b735f6c3'), ObjectId('69e63737b2c98212b735f6c4'), ObjectId('69e63737b2c98212b735f6c5'), ObjectId('69e63737b2c98212b735f6c6'), ObjectId('69e63737b2c98212b735f6c7'), ObjectId('69e63737b2c98212b735f6c8'), ObjectId('69e63737b2c98212b735f6c9'), ObjectId('69e63737b2c98212b735f6ca'), ObjectId('69e63737b2c98212b735f6cb'), ObjectId('69e63737b2c98212b735f6cc'), ObjectId('69e63737b2c98212b735f6cd'), ObjectId('69e63737b2c98212b735f6ce'), ObjectId('69e63737b2c98212b735f6cf'), ObjectId('69e63737b2c98212b735f6d0'), ObjectId('69e63737b2c98212b735f6d1'), ObjectId('69e63737b2c98212b735f6d2'), ObjectId('69e63737b2c98212b735f6d3'), ObjectId('69e63737b2c98212b735f6d4'), ObjectId('69e63737b2c98212b735f6d5'), ObjectId('69e63737b2c98212b735f6d6'), ObjectId('69e63737b2c98212b735f6d7'), ObjectId('69e63737b2c98212b735f6d8'), ObjectId('69e63737b2c98212b735f6d9'), ObjectId('69e63737b2c98212b735f6da'), ObjectId('69e63737b2c98212b735f6db'), ObjectId('69e63737b2c98212b735f6dc'), ObjectId('69e63737b2c98212b735f6dd'), ObjectId('69e63737b2c98212b735f6de'), ObjectId('69e63737b2c98212b735f6df'), ObjectId('69e63737b2c98212b735f6e0'), ObjectId('69e63737b2c98212b735f6e1'), ObjectId('69e63737b2c98212b735f6e2'), ObjectId('69e63737b2c98212b735f6e3'), ObjectId('69e63737b2c98212b735f6e4'), ObjectId('69e63737b2c98212b735f6e5'), ObjectId('69e63737b2c98212b735f6e6'), ObjectId('69e63737b2c98212b735f6e7'), ObjectId('69e63737b2c98212b735f6e8'), ObjectId('69e63737b2c98212b735f6e9'), ObjectId('69e63737b2c98212b735f6ea'), ObjectId('69e63737b2c98212b735f6eb'), ObjectId('69e63737b2c98212b735f6ec'), ObjectId('69e63737b2c98212b735f6ed'), ObjectId('69e63737b2c98212b735f6ee'), ObjectId('69e63737b2c98212b735f6ef'), ObjectId('69e63737b2c98212b735f6f0'), ObjectId('69e63737b2c98212b735f6f1'), ObjectId('69e63737b2c98212b735f6f2'), ObjectId('69e63737b2c98212b735f6f3'), ObjectId('69e63737b2c98212b735f6f4'), ObjectId('69e63737b2c98212b735f6f5'), ObjectId('69e63737b2c98212b735f6f6'), ObjectId('69e63737b2c98212b735f6f7'), ObjectId('69e63737b2c98212b735f6f8'), ObjectId('69e63737b2c98212b735f6f9'), ObjectId('69e63737b2c98212b735f6fa'), ObjectId('69e63737b2c98212b735f6fb'), ObjectId('69e63737b2c98212b735f6fc'), ObjectId('69e63737b2c98212b735f6fd'), ObjectId('69e63737b2c98212b735f6fe'), ObjectId('69e63737b2c98212b735f6ff'), ObjectId('69e63737b2c98212b735f700'), ObjectId('69e63737b2c98212b735f701'), ObjectId('69e63737b2c98212b735f702'), ObjectId('69e63737b2c98212b735f703'), ObjectId('69e63737b2c98212b735f704'), ObjectId('69e63737b2c98212b735f705'), ObjectId('69e63737b2c98212b735f706'), ObjectId('69e63737b2c98212b735f707'), ObjectId('69e63737b2c98212b735f708'), ObjectId('69e63737b2c98212b735f709'), ObjectId('69e63737b2c98212b735f70a'), ObjectId('69e63737b2c98212b735f70b'), ObjectId('69e63737b2c98212b735f70c'), ObjectId('69e63737b2c98212b735f70d'), ObjectId('69e63737b2c98212b735f70e'), ObjectId('69e63737b2c98212b735f70f'), ObjectId('69e63737b2c98212b735f710'), ObjectId('69e63737b2c98212b735f711'), ObjectId('69e63737b2c98212b735f712'), ObjectId('69e63737b2c98212b735f713')], acknowledged=True)